Vagrant.configure(2) do |config|
config.vm.box = "centos/8"
    config.vm.boot_timeout = 1000
    config.vm.define "ahintzS" do |control|
        control.vm.hostname = "ahintzS"
        control.vm.base_address = "192.168.42.110"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=774','fmode=775']
            control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "ahintzS"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.memory = 1024
            v.cpus = 2
            end
        config.vm.provision "file", source: "./", destination: "/home/vagrant/p2"
        control.vm.provision "shell", path: "scripts/master.sh"
        control.vm.provision "shell", path: "scripts/start.sh"
        end
end