Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.box_version = "3.5.0"
    config.vm.box_check_update = false
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  
    config.vm.provision "file", source: "./", destination: "/home/vagrant/p2"
    
    config.vm.boot_timeout = 1000
    config.vm.define "ahintzS" do |control|
      control.vm.hostname = "ahintzS"
      control.vm.network "private_network", ip: "192.168.42.110"
      control.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", "ahintzS"]
      end
      control.vm.provision "shell", path: "scripts/master.sh"
      control.vm.provision "shell", path: "scripts/start.sh"
    end
  end