Vagrant.configure(2) do |config|
config.vm.box = "centos/8"
    config.vm.define "ahintzS" do |control|
        control.vm.hostname = "ahintzS"
        control.vm.base_address = "192.168.42.110"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=774','fmode=775']
            control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "ahintzS"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.memory = 512
            v.cpus = 1
            end
        control.vm.provision "shell", path: "scripts/master.sh"
        end
    config.vm.define "ahintzSW" do |control|
        control.vm.hostname = "ahintzSW"
        control.vm.base_address = "192.168.42.111"
        control.vm.network "private_network", ip: "192.168.42.111"
        control.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=774','fmode=775']
            control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "ahintzSW"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.memory = 512
            v.cpus = 1
            end
        control.vm.provision "shell", path: "scripts/slave.sh"
        end
end